DROP TABLE ALUNOS;
DROP TABLE TELEFONES;
DROP TABLE PROFESSORES;
DROP TABLE DISCIPLINAS;
DROP TABLE OFERTAS;
DROP TABLE ALUNO_OFERTAS;
CREATE TABLE TELEFONES(
    TELEFONE VARCHAR2(11) NOT NULL,
    MATRICULA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS(
    MATRICULA NUMERIC NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE PROFESSORES(
    MATRICULA NUMERIC(5) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    FORMACAO VARCHAR2(100) NOT NULL
);

CREATE TABLE DISCIPLINAS(
    CODIGO_DISCIPLINA NUMERIC NOT NULL,
    NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
    CARGA_HORARIA NUMERIC(3) NOT NULL,
    EMENTA VARCHAR2(4000) NOT NULL,
    CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC
);

CREATE TABLE OFERTAS(
    CODIGO_OFERTA NUMERIC NOT NULL,
    HORARIO_INICIAL TIMESTAMP NOT NULL,
    HORARIO_FINAL TIMESTAMP NOT NULL,
    DIA_SEMANA VARCHAR2(20) NOT NULL,
    MATRICULA NUMERIC(5) NOT NULL,
    CODIGO_DISCIPLINA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS_OFERTAS(
    MATRICULA NUMERIC NOT NULL,
    CODIGO_OFERTA NUMERIC NOT NULL,
    LIMITE_ALUNOS NUMERIC NOT NULL,
    SEMESTRE VARCHAR2(10),
    DATA_INICIAL DATE NOT NULL,
    DATA_FINAL DATE NOT NULL
);
CREATE TABLE PROFESSORES(
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	NOME_PROF VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL
);CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARIO_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;
CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC NULL
);
CREATE TABLE OFERTAS(
	CODIGO_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR2(20) NOT NULL,
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	CODIGO_DISCIPLINA NUMERIC NOT NULL
);
CREATE TABLE ALUNO_OFERTAS(
	MATRICULA_ALUNO NUMERIC NOT NCREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARI);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);ULA_ALUNO;
ALTER TABLE OFERTAS 
O_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;ULL,
	CODIGO_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL
);
/*
 * 
 */
CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNOCREATE TABLE ALUNOS(
	MATRICULA_A);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);ULA_ALUNO;
ALTER TABLE OFERTAS 
LUNO NUMBER NOT NULL,
	NOME_ALUNO VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARIO_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;
/*
 * 
 */
CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS (NOME_ALUNO);

CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS (DIA_SEMANA);

CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES (NOME_PROF);
/*
 * 
 */
CREATE SEQUENCE DISCIPLINAS_SEQ;
CREATE SEQUENCE OFERTAS_SEQ;
/*
 * 
 */
ALTER TABLE ALUNOS ADD EMAIL VARCHAR2(200), CPF VARCHAR2(11) NOT NULL;
ALTER TABLE PROFESSORES ADD CONTATO VARCHAR2(200) NOT NULL;
ALTER TABLE OFERTAS ADD DATA_CRIACAO DATE NOT NULL;
ALTER TABLE ALUNOS MODIFY EMAIL VARCHAR2(200) NOT NULL;
ALTER TABLE OFERTAS MODIFY DATA_CRIACAO DATE NOT NULL DEFAULT SYSDATE;
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA NOME TO MATRICULA_ALUNO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA NOME TO MATRICULA_PROFESSOR NOME_PROFESSOR;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNOS_OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;
ALTER TABLE PROFESSORES DROP COLUMN CONTATO;
ALTER TABLE ALUNOS DROP COLUMN EMAIL;
ALTER TABLE ALUNOS DROP COLUMN CPF;
ALTER TABLE TELEFONES ADD PRIMARY KEY (TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY (MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD PRIMARY KEY (MATRICULA_ALUNO,CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD PRIMARY KEY (CODIGO_OFERTA);
ALTER TABLE PROFESSORES ADD PRIMARY KEY (MATRICULA_PROFESSOR);
ALTER TABLE DISCIPLINAS ADD PRIMARY KEY (CODIGO_DISCIPLINA);
ALTER TABLE TELEFONES_ALUNOS ADD CONSTRAINT TELEFONE_ALUNO_FK 
	FOREIGN KEY MATRICULA_ALUNO
	REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD CONSTRAINT ALUNOS_ALUNO_FK
	FOREIGN KEY MATRICULA_ALUNO
	REFERENCES 









